export default [
  {
    title: "igors life",
    desc: "viva com o igor",
    print: "/imgs/igor.png",
    linkGithub: "https://github.com/sopahaha/igors-life-alpha",
    linkPadrao: "https://sopahaha.github.io/igors-life-alpha/",
  },
  {
    title: "cryptografia de ponta",
    desc: "defil de descifrar",
    print: "/imgs/crypto.png",
    linkGithub: "https://github.com/sopahaha/crypto",
  },
  {
    title: "sistema sopar",
    desc: "sistema solar real igual da vida real",
    print: "/imgs/sistemasopar.png",
    linkGithub: "https://github.com/sopahaha/sistema-sopar",
    linkPadrao: "https://sopahaha.github.io/sistema-sopar/",
  },
  {
    title: "jardim dos atumalacas",
    desc: "super desafio epico",
    print: "/imgs/atuma.png",
    linkGithub: "https://github.com/sopahaha/atumalaca",
    linkPadrao: "https://sopahaha.github.io/atumalaca/",
  },
  {
    title: "radio tauz v1",
    desc: "comeco de um sonho, me tornei um grande ninja",
    print: "/imgs/radiotauz.png",
    linkGithub: "https://github.com/sopahaha/radio-tauz",
    linkPadrao: "https://sopahaha.github.io/radio-tauz/",
  },
  {
    title: "togs loves",
    desc: "uma das minhas maiores criacoes",
    print: "/imgs/tlove.png",
    linkGithub: "https://github.com/sopahaha/t-love",
    linkPadrao: "",
  },
  {
    title: "windows 10",
    desc: "esse enganava todo mundo no f11",
    print: "/imgs/w10.png",
    linkGithub: "https://github.com/sopahaha/windows10",
    linkPadrao: "https://sopahaha.github.io/windows10/",
  },
  {
    title: "radio tauz absoluto",
    desc: "super radio do tauz pode colocar de wallpaper no wp engine",
    print: "/imgs/radiotauz2.png",
    linkGithub: "https://github.com/sopahaha/radio-tauz-deluxe",
    linkPadrao: "https://radio-tauz-deluxe.vercel.app/",
  },
  {
    title: "togs six seven",
    desc: "use o togs 67 para decidir as coisa, nunca mais cara ou coroa",
    print: "/imgs/togs67.png",
    linkGithub: "https://github.com/sopahaha/togs-67",
    linkPadrao: "https://sopahaha.github.io/togs-67/",
  },
];
